baseURL = "https://uccs.codeberg.page/"
languageCode = "ro-RO"
defaultContentLanguage = "ro"
title = "Unde Cuvintele Capătă Sens"
enableRobotsTXT = true
enableGitInfo = true
summaryLength = 30
pagination.pagerSize = 10
theme = "uccs-theme-a"

[permalinks]
    analyticus = "/analyticus/:slug/"
    cultural = "/cultural/:slug/"
    dezbateri = "/dezbateri/:slug/"

[taxonomies]
    tag = "tags"
    author = "authors"
    theme = "themes"

[outputs]
    home = ["HTML", "RSS"]
    section = ["HTML", "RSS"]
    page = ["HTML"]

[markup]
defaultMarkdownHandler = "pandoc"

[security]
  enableInlineShortcodes = false

  [security.exec]
    allow = ['^git$', '^pandoc$']
    osEnv = ['(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|GO\\w+|(XDG_CONFIG_)?HOME|USERPROFILE|SSH_AUTH_SOCK|DISPLAY|LANG|SYSTEMDRIVE|PROGRAMDATA)$']

  [security.funcs]
    getenv = ['^HUGO_', '^CI$']

  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']
